### ISSUE TITLE
Throw Errors instead of Strings

### ISSUE THREAD

**Issue by marcbachmann** [janl/node-jsonpointer#11]
Is there a reason you throw strings instead of errors?
That's an unusual behaviour.

**Comment by gabe0x02** [comment]
/bump 
It's really hard to do error handling correctly with this.  Especially since you throw the error on a valid path that is just not found in the object.  Separate issue: maybe that should just return undefined instead of throwing an error.

**Comment by janl** [comment]
Pros welcome.

**Comment by janl** [comment]
fixed in #17
