### ISSUE TITLE
Non-compliant for `/foo/01` and `/foo/-`

### ISSUE THREAD

**Issue by emilbayes** [janl/node-jsonpointer#14]
The pointers `/foo/01` and `/foo/-` do not yet seem to be implemented here. I made a quick implementation here: https://gist.github.com/emilbayes/e6b740529147a72205f0

**Comment by janl** [comment]
@emilbayes wanna send a pull request? :)

**Comment by emilbayes** [comment]
Hehe, I considered it, but it seemed like too much work trying to understand your implementation, hence the commented gist :)

**Comment by janl** [comment]
I don’t have time to transform the code. If you want to see this in the project, I need something that I can merge :)

**Comment by marcbachmann** [comment]
According to the RFC, leading zeros aren't allowed.
http://tools.ietf.org/html/rfc6901#section-4

>   o  If the currently referenced value is a JSON array, the reference
>      token MUST contain either:
>
>      *  characters comprised of digits (see ABNF below; note that
>         leading zeros are not allowed) that represent an unsigned
>         base-10 integer value, making the new referenced value the
>         array element with the zero-based index identified by the
>         token, or

**Comment by marcbachmann** [comment]
IMO we can close this.

Concerning the error handling:
This library currently returns `null` when a pointer references a non-existing value.
According to the spec this behavior can vary between implementations and should be documented.

https://tools.ietf.org/html/rfc6901#section-7

> 7.  Error Handling

>    In the event of an error condition, evaluation of the JSON Pointer
>    fails to complete.

>    Error conditions include, but are not limited to:

>    o  Invalid pointer syntax

>    o  A pointer that references a nonexistent value

>    This specification does not define how errors are handled.  An
>    application of JSON Pointer SHOULD specify the impact and handling of
>    each type of error.

>    For example, some applications might stop pointer processing upon an
>    error, while others may attempt to recover from missing values by
>    inserting default ones.
