### ISSUE TITLE
Issue with `request-promise` and Webpack

### ISSUE THREAD

**Issue by matthewgertner** [janl/node-jsonpointer#16]
Is the line `var console = require("console");` needed at the top of the `jsonpointer.js`? I can't see the variable used elsewhere in the file, and it's breaking Webpack when `request-promise` is used (see https://github.com/webpack/webpack/issues/1019). Would you consider a pull request that removes it?

**Comment by marcbachmann** [comment]
No, that's not needed. It's not even in the dependencies.
Yes, you can create a pr if you like.

**Comment by marcbachmann** [comment]
Fixed in #18. Thanks
