### ISSUE TITLE
CLI usage

### ISSUE THREAD

**Issue by joeyespo** [janl/node-jsonpointer#29]
Just a heads up that I published [jsonpointer-cli](https://github.com/joeyespo/jsonpointer-cli), which lets you use this project on the command line.

I linked it to this project since it's implemented with it. Would you be open to doing the same? Something like:

```
## CLI

Looking to filter JSON from the command line? Check out [jsonpointer-cli](https://github.com/joeyespo/jsonpointer-cli).
```

If not, feel free to close. No hard feelings, just thought I'd ask :smiley:

**Comment by marcbachmann** [comment]
👍  Will do

can you publish the module again, so the README is available on npm? https://www.npmjs.com/package/jsonpointer-cli

**Comment by joeyespo** [comment]
Awesome! Thank you!

I contacted npm about the missing README. Looks like there was a rendering bug. It's up now 😄

**Comment by janl** [comment]
Finally committed, thanks! :)

**Comment by joeyespo** [comment]
Thank you, @janl! 😃
