### ISSUE TITLE
Does the typescript typings file work?

### ISSUE THREAD

**Issue by marcbachmann** [janl/node-jsonpointer#36]
I just saw that in the `files` property in the package.json we only list the `jsonpointer.js` file but not the `jsonpointer.d.ts` file. Isn't that needed in the package to get typescript working?
I'm not using typescript myself, so I have no idea how to verify that.

https://github.com/janl/node-jsonpointer/blob/master/package.json#L27-L30

**Comment by janl** [comment]
hm I trusted the PR knew what they were doing :)

**Comment by robertmassaioli** [comment]
I don't think the types file is being picked up. I had to manually copy it into my project.

**Comment by FabianFrank** [comment]
The typings file doesn't work, it's not included in the package published to the npm registry.
