### ISSUE TITLE
Add a github release

### ISSUE THREAD

**Issue by Sytten** [janl/node-jsonpointer#55]
Hi
Could you please add a github release with the v5 changes. I got a vulnerability advisory for anything <v5 but I have no clue if major stuff broke in v5.
Thanks.

**Comment by CarolynWebster** [comment]
Came here looking for the same thing - are there any breaking changes on v5.0.0?

**Comment by marcbachmann** [comment]
`__proto__`, `constructor` and `prototype` keys are not supported anymore.
And if you pass non-string arrays to the .get and .set functions, it will also throw.

https://github.com/janl/node-jsonpointer/blob/main/test.js#L131-L161

**Comment by marcbachmann** [comment]
I've quickly drafted the release https://github.com/janl/node-jsonpointer/releases/tag/v5.0.0
