### ISSUE TITLE
Pre-compile pointer?

### ISSUE THREAD

**Issue by hildjj** [janl/node-jsonpointer#8]
What do you think about the ability to pre-compile a pointer?  This would return a function that might be slightly faster for querying, but slower to create than the current approach.  For applications where you're making the same query over and over, this would be a win.

**Comment by marcbachmann** [comment]
I've merged the compile functionality with the api
```js
var pointer = jsonpointer.compile('/path')
pointer.get(object)
pointer.set(object, value)
```
